Ref: Post.userId > User.id
Ref: Post.locationId > Location.id
Ref: Comment.userId > User.id
Ref: Comment.postId > Post.id
Ref: Comment.parentCommentId > Comment.id
Ref: PostReaction.userId > User.id
Ref: PostReaction.postId > Post.id
Ref: PostReaction.reactionId > Reaction.id
Ref: PostPhotos.postId > Post.id
Ref: Subscriptions.userId > User.id
Ref: Subscriptions.subscriberId > User.id